default_style = "cap"

colorscheme = "cap"

default_completed_emoji = "[green]✔[/green]"
default_incompleted_emoji = "kf"

# completed_style = "dim/strikethrough/green/normal"
#completed_style = "dim strike"
#completed_style = "dim"
completed_style = ""
